// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkZV_qkrgJHO7zw3ie0Tgfe7zcRDsfK-g',
    appId: '1:808210283479:web:c892f078f7b79fdf48e992',
    messagingSenderId: '808210283479',
    projectId: 'demo2-18bbe',
    authDomain: 'demo2-18bbe.firebaseapp.com',
    databaseURL: 'https://demo2-18bbe-default-rtdb.firebaseio.com',
    storageBucket: 'demo2-18bbe.firebasestorage.app',
    measurementId: 'G-QWR7YHK8E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_rY7l7MBJnbBFKLRvtK4aoV8s3Ivdzxo',
    appId: '1:808210283479:android:4611d8473bce968748e992',
    messagingSenderId: '808210283479',
    projectId: 'demo2-18bbe',
    databaseURL: 'https://demo2-18bbe-default-rtdb.firebaseio.com',
    storageBucket: 'demo2-18bbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9EYX9Ol5A514V5koRq1I4SB0nb73f-KY',
    appId: '1:808210283479:ios:a80e106ffb6e7d5948e992',
    messagingSenderId: '808210283479',
    projectId: 'demo2-18bbe',
    databaseURL: 'https://demo2-18bbe-default-rtdb.firebaseio.com',
    storageBucket: 'demo2-18bbe.firebasestorage.app',
    iosBundleId: 'com.example.virmedo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9EYX9Ol5A514V5koRq1I4SB0nb73f-KY',
    appId: '1:808210283479:ios:a80e106ffb6e7d5948e992',
    messagingSenderId: '808210283479',
    projectId: 'demo2-18bbe',
    databaseURL: 'https://demo2-18bbe-default-rtdb.firebaseio.com',
    storageBucket: 'demo2-18bbe.firebasestorage.app',
    iosBundleId: 'com.example.virmedo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkZV_qkrgJHO7zw3ie0Tgfe7zcRDsfK-g',
    appId: '1:808210283479:web:e2c9f63a7528393f48e992',
    messagingSenderId: '808210283479',
    projectId: 'demo2-18bbe',
    authDomain: 'demo2-18bbe.firebaseapp.com',
    databaseURL: 'https://demo2-18bbe-default-rtdb.firebaseio.com',
    storageBucket: 'demo2-18bbe.firebasestorage.app',
    measurementId: 'G-SZ8R86B9ZL',
  );

}